gap> START_TEST("AdditiveClosureObjFinDirectSum.tst");
gap> 
gap> LoadPackage( "FiniteCocompletions", false );
true
gap> LoadPackage( "FreydCategoriesForCAP", false );
true
gap> LoadPackage( "SubcategoriesForCAP", false );
true
gap> 
gap> Q := HomalgFieldOfRationals();
Q
gap> rows := CategoryOfRows( Q );;
gap> 
gap> a := CategoryOfRowsObject( rows, 1 );;
gap> b := CategoryOfRowsObject( rows, 2 );;
gap> c := CategoryOfRowsObject( rows, 3 );;
gap> 
gap> subcat := FullSubcategoryGeneratedByListOfObjects( [ a, b, c ] );
Full subcategory generated by 3 objects in Rows( Q )
gap> 
gap> a := a / subcat;
An object in full subcategory given by: <A row module over Q of rank 1>
gap> b := b / subcat;
An object in full subcategory given by: <A row module over Q of rank 2>
gap> c := c / subcat;
An object in full subcategory given by: <A row module over Q of rank 3>
gap> 
gap> dac := DisconnectedAdditiveClosure( subcat );
DisconnectedAdditiveClosure( Full subcategory generated by 3 objects in Rows( \
Q ) )
gap> ac_objfin := ModelingCategory( dac );
AdditiveClosureOfObjectFiniteCategory( Full subcategory generated by 3 objects\
 in Rows( Q ) )
gap> 
gap> #########################################
gap> # Objects
gap> #########################################
gap> 
gap> # Taking the model and then the reinterpretation on objects is the identity: (dac -> ac_objfin -> dac) = id
gap> 
gap> a1_reinterp := ObjectConstructor( dac, [5,[2,2,1]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> a2_reinterp := ObjectConstructor( dac, [2,[1,1,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> a1_model := ModelingTowerObjectConstructor( dac, ObjectDatum( a1_reinterp ) );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> a2_model := ModelingTowerObjectConstructor( dac, ObjectDatum( a2_reinterp ) );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> 
gap> a1_reinterp = ObjectConstructor( dac, ModelingTowerObjectDatum( dac, a1_model ) );
true
gap> a2_reinterp = ObjectConstructor( dac, ModelingTowerObjectDatum( dac, a2_model ) );
true
gap> 
gap> # Taking the reinterpretation and then the model on objects is only an isomorphism and not the identity: (ac_objfin -> dac -> ac_objfin) =/= id.
gap> # This is due to the sorting/reordering in the reinterpretation.
gap> 
gap> a1_model := ObjectConstructor( ac_objfin, [5,[2,2,1]] );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> a2_model := ObjectConstructor( ac_objfin, [2,[1,1,0]] );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> 
gap> a1_model = ModelingTowerObjectConstructor( dac, ObjectDatum( a1_reinterp ) );
true
gap> a2_model = ModelingTowerObjectConstructor( dac, ObjectDatum( a2_reinterp ) );
true
gap> 
gap> #########################################
gap> # Morphisms
gap> #########################################
gap> 
gap> a := CategoryOfRowsObject( rows, 1 );;
gap> b := CategoryOfRowsObject( rows, 2 );;
gap> c := CategoryOfRowsObject( rows, 3 );;
gap> 
gap> # Taking the reinterpretation and then the model on morphisms gives the identity: ac_objfin -> dac -> ac_objfin
gap> # Construct a morphism in the model ac_objfin.
gap> 
gap> m11 := MorphismConstructor( rows, a, HomalgMatrix( [ [0] ], 1, 1, Q ), a ) / subcat;;
gap> m12 := ZeroMorphism( rows, a, b ) / subcat;;
gap> m21 := MorphismConstructor( rows, a, HomalgMatrix( [ [9] ], 1, 1, Q ), a ) / subcat;;
gap> m22 := ZeroMorphism( rows, a, b ) / subcat;;
gap> m31 := ZeroMorphism( rows, b, a ) / subcat;;
gap> m32 := MorphismConstructor( rows, b, HomalgMatrix( [ [3,2], [5,1] ], 2, 2, Q ), b ) / subcat;;
gap> m41 := ZeroMorphism( rows, b, a ) / subcat;;
gap> m42 := MorphismConstructor( rows, b, HomalgMatrix( [ [3,1], [1,2] ], 2, 2, Q ), b ) / subcat;;
gap> m51 := ZeroMorphism( rows, c, a ) / subcat;;
gap> m52 := ZeroMorphism( rows, c, b ) / subcat;;
gap> 
gap> source := ObjectConstructor( ac_objfin, [ 5, [2,2,1] ] );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> target := ObjectConstructor( ac_objfin, [ 2, [1,1,0] ] );
<An object in AdditiveClosureOfObjectFiniteCategory( Full subcategory generate\
d by 3 objects in Rows( Q ) )>
gap> matrix := [ [m11,m12], [m21,m22], [m31,m32], [m41,m42], [m51,m52] ];;
gap> mor_model := MorphismConstructor( ac_objfin, source, matrix, target );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( ac_objfin, mor_model );
true
gap> 
gap> # Take the reinterpretation of mor_model.
gap> 
gap> source_reinterp := ReinterpretationOfObject( dac, Source( mor_model ) );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> target_reinterp := ReinterpretationOfObject( dac, Target( mor_model ) );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> mor_reinterp := ReinterpretationOfMorphism( dac, source_reinterp, mor_model, target_reinterp );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor_reinterp );
true
gap> mor_model = ModelingMorphism( dac, mor_reinterp );
true
gap> 
gap> # Taking the model and then the reinterpretation on morphism is the identity: dac -> ac_objfin -> dac = id.
gap> # First construct a morphism in dac.
gap> 
gap> list_of_matrices := [ [ [m11],[m21] ], [ [m32],[m42] ], [ [] ] ];;
gap> mor_reinterp := MorphismConstructor( dac, a1_reinterp, list_of_matrices, a2_reinterp );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor_reinterp );
true
gap> mor_model := ModelingMorphism( dac, mor_reinterp );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> 
gap> source_reinterp := ReinterpretationOfObject( dac, Source( mor_model ) );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> target_reinterp := ReinterpretationOfObject( dac, Target( mor_model ) );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> mor_reinterp = ReinterpretationOfMorphism( dac, source_reinterp, mor_model, target_reinterp );
true
gap> 
gap> ##################################################################################
gap> # Check some corner cases
gap> ##################################################################################
gap> 
gap> zero := ObjectConstructor( dac, [0,[0,0,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [], [], [] ];
[ [  ], [  ], [  ] ]
gap> zero_mor := MorphismConstructor( dac, zero, list_of_matrices, zero );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefined( zero_mor );
true
gap> zero_mor_model := ModelingMorphism( dac, zero_mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> IsEmpty( MorphismMatrix( zero_mor_model ) );
true
gap> zero_mor = ZeroMorphism( dac, zero, zero );
true
gap> zero_mor_reinterp := ReinterpretationOfMorphism( dac, zero, zero_mor_model, zero );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( zero_mor_reinterp );
true
gap> 
gap> source := ObjectConstructor( dac, [2,[0,2,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [], [ [], [] ], [] ];
[ [  ], [ [  ], [  ] ], [  ] ]
gap> mor := MorphismConstructor( dac, source, list_of_matrices, zero );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor );
true
gap> mor_model := ModelingMorphism( dac, mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> MorphismMatrix( mor_model ) = [ [], [] ];
true
gap> mor_reinterp := ReinterpretationOfMorphism( dac, source, mor_model, zero );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( mor_reinterp );
true
gap> 
gap> target := ObjectConstructor( dac, [2,[0,2,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [], [], [] ];
[ [  ], [  ], [  ] ]
gap> mor := MorphismConstructor( dac, zero, list_of_matrices, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor );
true
gap> mor_model := ModelingMorphism( dac, mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> MorphismMatrix( mor_model ) = [ ];
true
gap> mor_reinterp := ReinterpretationOfMorphism( dac, zero, mor_model, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( mor_reinterp );
true
gap> 
gap> source := ObjectConstructor( dac, [1,[0,1,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> target := ObjectConstructor( dac, [2,[1,1,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [], [ [ m32 ] ], [] ];
[ [  ], 
  [ [ A morphism in full subcategory given by: <A morphism in Rows( Q )> ] ], 
  [  ] ]
gap> mor := MorphismConstructor( dac, source, list_of_matrices, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor );
true
gap> mor_model := ModelingMorphism( dac, mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> zero_subcat := ZeroMorphism( rows, b, a )  / subcat;
A morphism in full subcategory given by: <A zero morphism in Rows( Q )>
gap> MorphismMatrix( mor_model ) = [ [ zero_subcat, m32 ] ];
true
gap> mor_reinterp := ReinterpretationOfMorphism( dac, source, mor_model, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( mor_reinterp );
true
gap> 
gap> source := ObjectConstructor( dac, [2,[1,1,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> target := ObjectConstructor( dac, [2,[0,2,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [ [] ], [ [ m32, m32 ] ], [] ];
[ [ [  ] ], 
  [ [ A morphism in full subcategory given by: <A morphism in Rows( Q )>, 
          A morphism in full subcategory given by: <A morphism in Rows( Q )> 
         ] ], [  ] ]
gap> mor := MorphismConstructor( dac, source, list_of_matrices, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor );
true
gap> mor_model := ModelingMorphism( dac, mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> zero_subcat := ZeroMorphism( rows, a, b )  / subcat;
A morphism in full subcategory given by: <A zero morphism in Rows( Q )>
gap> MorphismMatrix( mor_model ) = [ [ zero_subcat, zero_subcat ], [ m32, m32 ] ];
true
gap> mor_reinterp := ReinterpretationOfMorphism( dac, source, mor_model, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( mor_reinterp );
true
gap> 
gap> source := ObjectConstructor( dac, [1,[0,1,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> target := ObjectConstructor( dac, [1,[1,0,0]] );
<An object in DisconnectedAdditiveClosure( Full subcategory generated by 3 obj\
ects in Rows( Q ) )>
gap> list_of_matrices := [ [], [ [] ], [] ];
[ [  ], [ [  ] ], [  ] ]
gap> mor := MorphismConstructor( dac, source, list_of_matrices, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> IsWellDefinedForMorphisms( mor );
true
gap> mor_model := ModelingMorphism( dac, mor );
<A morphism in AdditiveClosureOfObjectFiniteCategory( Full subcategory generat\
ed by 3 objects in Rows( Q ) )>
gap> zero_subcat := ZeroMorphism( rows, b, a )  / subcat;
A morphism in full subcategory given by: <A zero morphism in Rows( Q )>
gap> MorphismMatrix( mor_model ) = [ [ zero_subcat] ];
true
gap> mor_reinterp := ReinterpretationOfMorphism( dac, source, mor_model, target );
<A morphism in DisconnectedAdditiveClosure( Full subcategory generated by 3 ob\
jects in Rows( Q ) )>
gap> list_of_matrices = ListOfMatrices( mor_reinterp );
true
gap> 
gap> STOP_TEST("AdditiveClosureObjFinDirectSum.tst", 1);

